import unittest
from wrapt_timeout_decorator import timeout
from integer_container_impl import IntegerContainerImpl


class SandboxTests(unittest.TestCase):
    """
    The test class below can be considered as a playground - feel free to modify it as you need, e.g.:
    - add your own custom tests
    - delete existing tests
    - modify test contents or expected output

    The results of tests from this file will always be at the beginning of the report generated by clicking the "Run" button.

    The results of these tests do not affect the final score (unless the project fails to build).
    """

    failureException = Exception


    def setUp(self):
        self.container = IntegerContainerImpl()

    @timeout(0.4)
    def test_level_1(self):
        pass
