import unittest
from memory_database_impl import MemoryDatabaseBasicImpl, MemoryDatabaseAdvancedImpl

class SandboxTests(unittest.TestCase):
    """
    The test class below can be considered as a playground - feel free to modify it as you need, e.g.:
    - add your own custom tests
    - delete existing tests
    - modify test contents or expected output

    The results of tests from this file will always be at the beginning of the report generated by clicking the "Run" button.

    The results of these tests do not affect the final score (unless the project fails to build).
    """

    failureException = Exception

    def setUp(self):
        self.basic = MemoryDatabaseBasicImpl()
        self.advanced = MemoryDatabaseAdvancedImpl()

    def test_level_1(self):
        db = self.basic
        db.set("A", "B", "E")
        db.set("A", "C", "F")
        self.assertEqual(db.get("A", "B"), "E")
        self.assertIsNone(db.get("A", "D"))
        self.assertTrue(db.delete("A", "B"))
        self.assertFalse(db.delete("A", "D"))

    def test_level_2(self):
        db = self.basic
        db.set("A", "BC", "E")
        db.set("A", "BD", "F")
        db.set("A", "C", "G")
        self.assertEqual(db.scan_by_prefix("A", "B"), ["BC(E)", "BD(F)"])
        self.assertEqual(db.scan("A"), ["BC(E)", "BD(F)", "C(G)"])
        self.assertEqual(db.scan_by_prefix("B", "B"), [])

    def test_level_3_case_1(self):
        db = self.advanced
        db.set_at_with_ttl("A", "BC", "E", 1, 9)
        db.set_at_with_ttl("A", "BC", "E", 5, 10)
        db.set_at("A", "BD", "F", 5)
        self.assertEqual(db.scan_by_prefix_at("A", "B", 14), ["BC(E)", "BD(F)"])
        self.assertEqual(db.scan_by_prefix_at("A", "B", 15), ["BD(F)"])

    def test_level_3_case_2(self):
        db = self.advanced
        db.set_at("A", "B", "C", 1)
        db.set_at_with_ttl("X", "Y", "Z", 2, 15)
        self.assertEqual(db.get_at("X", "Y", 3), "Z")
        db.set_at_with_ttl("A", "D", "E", 4, 10)
        self.assertEqual(db.scan_at("A", 13), ["B(C)", "D(E)"])
        self.assertEqual(db.scan_at("X", 16), ["Y(Z)"])
        self.assertEqual(db.scan_at("X", 17), [])
        self.assertFalse(db.delete_at("X", "Y", 20))

    def test_level_4(self):
        db = self.advanced
        db.set_at_with_ttl("A", "B", "C", 1, 10)
        self.assertEqual(db.backup(3), 1)
        db.set_at("A", "D", "E", 4)
        self.assertEqual(db.backup(5), 1)
        self.assertTrue(db.delete_at("A", "B", 8))
        self.assertEqual(db.backup(9), 1)
        db.restore(10, 7)
        self.assertEqual(db.backup(11), 1)
        self.assertEqual(db.scan_at("A", 15), ["B(C)", "D(E)"])
        self.assertEqual(db.scan_at("A", 16), ["D(E)"])